### ISSUE TITLE
Exceeds token limit

### ISSUE THREAD

**Issue by lukastom** [ahmedkhaleel2004/gitdiagram#1]
So, I tried the tool on https://github.com/illacloud/illa-builder and the result is: "File tree and README combined exceeds token limit (50,000). Current size: 78518 tokens"

**Comment by ahmedkhaleel2004** [comment]
I am currently hosting the site for free so I'm trying to reduce costs, sorry! I have set a max limit of 50k tokens for the input, so if the repository is too large, it will reject. If you want the diagram, you can run it locally! The steps are in the README

I also plan on letting people bypass this by inputting their own API key (never stored of course)

**Comment by lukastom** [comment]
Great, thank you :-) Maybe you could just add this info to the error.

**Comment by ahmedkhaleel2004** [comment]
will do.
