### ISSUE TITLE
Syntax error in text mermaid version 11.4.1

### ISSUE THREAD

**Issue by BoBeR182** [ahmedkhaleel2004/gitdiagram#2]
https://gitdiagram.com/ssl/ezXSS

Syntax error in text
mermaid version 11.4.1

**Comment by ahmedkhaleel2004** [comment]
<img width="485" alt="image" src="https://github.com/user-attachments/assets/fdbb5af9-3305-4320-981a-88e90698dc52" />

so claude seems to have not generated these node names as a string

**Comment by BoBeR182** [comment]
Fixed by rerunning
https://gitdiagram.com/ssl/ezXSS

**Comment by BoBeR182** [comment]
Unless you want to catch this bug in the code, you can close if it's a WON'T FIX
